Re-implement classic quarried stone gen
railcraft-reborn/railcraft pull request #230
Opened 2024-07-17 18:07 UTC by andreblanke

**The Issue**

Railcraft Reborn currently generates quarried stone using the regular `minecraft:ore` feature. I've always liked the more unique ways Railcraft used to generate resources and would thus like to see it reintroduced.
 
**The Proposal**

This PR restores the classic quarried stone generation using a custom `railcraft:quarried` feature. The old generation logic has mostly been ported over and is made a bit more flexible through the use of `QuarryConfiguration` as configured feature, allowing configuration of the blocks to place (i.e., `railcraft:quarried_stone` by default) and the target blocks which are allowed to be replaced during generation (i.e., all blocks matched by the newly introduced `#railcraft:quarried_replaceable_blocks` tag).

**Possible Side Effects**

I'm not aware of any side effects except changing the generated amount of quarried stone back to its original amount which is likely lower than the amount currently generated using the `minecraft:ore` feature.
 
**Alternatives**

The alternative would be to keep the status quo.

2024-07-18 07:50 UTC, Edivad99 commented
Run `./gradlew spotlessApply` to fix the formatting

2024-07-18 07:55 UTC, Edivad99 requested changes

2024-07-18 07:55 UTC, Edivad99 commented on src/main/java/mods/railcraft/world/level/levelgen/feature/RailcraftFeatures.java
> +    private static final DeferredRegister<Feature<?>> FEATURES =
I know it's right to put `FEATURES`, but better to put `deferredRegister` for consistency with the rest. One day I'll change the name of all of them.
```suggestion
    private static final DeferredRegister<Feature<?>> deferredRegister =
```

2024-07-18 07:55 UTC, Edivad99 commented on src/main/java/mods/railcraft/world/level/levelgen/feature/RailcraftFeatures.java
> +        FEATURES.register("quarried", () -> new QuarriedFeature(QuarriedConfiguration.CODEC));
```suggestion
        deferredRegister.register("quarried", () -> new QuarriedFeature(QuarriedConfiguration.CODEC));
```

2024-07-18 07:55 UTC, Edivad99 commented on src/main/java/mods/railcraft/world/level/levelgen/feature/RailcraftFeatures.java
> +        FEATURES.register(eventBus);
```suggestion
        deferredRegister.register(eventBus);
```

2024-07-20 10:07 UTC, Edivad99 approved these changes

2024-07-20 10:09 UTC, andreblanke commented
Sorry for that, I was just about to push the changes you requested

2024-07-20 10:11 UTC, Edivad99 commented
Oops, I wanted to test it and ended up fixing a few things😅

2024-07-20 10:12 UTC, Edivad99 commented
Well done, by the way👏🏻

2024-07-20 12:03 UTC, merged

2024-07-21 06:38 UTC, andreblanke commented
> Well done, by the way👏🏻

Thank you, also for resolving the remaining formatting issues and merging it. I might look into the sulfur world generation as well.

2024-07-21 08:04 UTC, Edivad99 commented
Ok, so I'm waiting to do the release for 1.21. I was thinking of doing it today, but now I'll wait.

2024-07-21 10:31 UTC, andreblanke commented
I might be able to finish it today, but I could use some input regarding the generation details. I've started the discussion #231 for it.