Ore generation
railcraft-reborn/railcraft pull request #25
Opened 2021-12-18 13:47 UTC by LetterN

2021-12-18 14:39 UTC, Sm0keySa1m0n requested changes

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on build.gradle
> +      // Forge (this is the new url)
Remove the comment, re-add the repo name

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on build.gradle
> +      // Mixin
Remove comment, re-add the sponge repo name

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on build.gradle
> +// apply from: 'https://raw.githubusercontent.com/SizableShrimp/Forge-Class-Remapper/main/classremapper.gradle'
Just completely remove this, forgot to remove it myself

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on build.gradle
> -    minecraft group: 'net.minecraftforge', name: 'forge', version: "${project.minecraft_version}-${project.forge_version}"
Add this back

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on src/main/java/mods/railcraft/Railcraft.java
> +    catch (IOException e){
Move this up onto the same line as the close bracket (like with if/else)

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on src/main/java/mods/railcraft/Railcraft.java
> -  public void handleWorldTick(TickEvent.WorldTickEvent event) {
Add this back (maybe change your formatter settings if this was done by your IDE)

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on src/main/java/mods/railcraft/data/worldgen/RailcraftConfigurableOre.java
> +    this.placementType = this.placementTypeConfig.get();
Why are you copying these values? (Why can't you just reference the config directly)

2021-12-18 14:39 UTC, Sm0keySa1m0n commented on src/main/java/mods/railcraft/world/level/block/RailcraftBlocks.java
> +  // UNUSED! ONLY FOR 1.16 BACKPORT
Not planning on doing back ports at this point, just remove

2022-08-28 09:53 UTC, LetterN commented
ded pr

2022-08-28 09:53 UTC, closed without merging